### ISSUE TITLE
The problem of the top 1 acc

### ISSUE THREAD

**Issue by plzhang4321** [AndrewAtanov/simclr-pytorch#1]
what means "it may be in std" .  Your awesome implementation in pytorch, but I cnnnot understand its big drop~

**Comment by senya-ashukha** [comment]
It means that results can differ depending on a random seed. This is an expansive setup that takes 16v100 and 170h and we tried it only once. Also, there is a mismatch in default PyTorch and TF augmentation of ImageNet images, in PyTorch to the best of my knowledge there is no min_object_covered parameter https://github.com/google-research/simclr/blob/3fb622131d1b6dee76d0d5f6aac67db84dab3800/data_util.py#L269.

**Comment by plzhang4321** [comment]
Thank you~
