### ISSUE TITLE
linear fc layer

### ISSUE THREAD

**Issue by jiayini1119** [AndrewAtanov/simclr-pytorch#14]
When I printed the model, it shows that there is an fc layer after avgpool and before the projection. However, in the forward method of the ResNet, I didn't see fc layer being used. I was wondering where the fc linear layer is used. Thanks!

**Comment by AndrewAtanov** [comment]
Hello @jiayini1119. We do not use the fc layer. It's defined in the original codebase and we simply discard it.

**Comment by jiayini1119** [comment]
@AndrewAtanov I see. Thanks for your response!
