### ISSUE TITLE
Checkpoints and linear evaluation

### ISSUE THREAD

**Issue by ferumchrome** [AndrewAtanov/simclr-pytorch#6]
Hi! Thanks for releasing this repo!

I have a question about training and evaluation. When the model is trained (on cifar10), several checkpoints are saved, so which one should I use to for linear evaluation: checkpoint-48000 or checkpoint?

Also, am I right that this last column shows the final accuracy of linear evaluation that you report?

![simclr_repo_q](https://user-images.githubusercontent.com/26934115/134530573-e2f0a08a-ec0a-4e50-aa6c-00626cc4a112.png)

**Comment by senya-ashukha** [comment]
Hi Artem,

> checkpoints

They are likely the same. But it is safe to use "checkpoint".

> last column

Yep, that is an artifact of a printing code. The code will print a header again at some point see [ref](https://github.com/AndrewAtanov/simclr-pytorch/blob/master/utils/logger.py#L55).
