### ISSUE TITLE
no image normalization

### ISSUE THREAD

**Issue by kaiwenzha** [AndrewAtanov/simclr-pytorch#7]
Hi, thanks for your great work! 

I was wondering why there is no channel normalization (transforms.Normalize) for ImageNet and CIFAR?

**Comment by AndrewAtanov** [comment]
Hi!

We closely followed the original implementation here and (if I’m not mistaken) didn’t play with normalization. Given the strong color jitterring, it probably wouldn’t be helpful, but this is only the guess. Let us know the outcome if you try! :)

**Comment by kaiwenzha** [comment]
Thank you! now it's clear to me :)
